#! /bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2024-2026 Oracle.  All Rights Reserved.
#
# FS QA Test No. 662
#
# Ensure that autonomous self healing works fixes the filesystem correctly
# even if the spot repair doesn't work and it falls back to a full fsck.
#
. ./common/preamble
_begin_fstest auto selfhealing

. ./common/filter
. ./common/fuzzy
. ./common/systemd

_require_scrub
_require_xfs_io_command "repair"	# online repair support
_require_xfs_db_command "blocktrash"
_require_command "$XFS_HEALER_PROG" "xfs_healer"
_require_command "$XFS_PROPERTY_PROG" "xfs_property"
_require_scratch
_require_systemd_unit_defined "xfs_scrub@.service"

_scratch_mkfs >> $seqres.full
_scratch_mount

_xfs_has_feature $SCRATCH_MNT rmapbt || \
	_notrun "reverse mapping required to test directory auto-repair"
_xfs_has_feature $SCRATCH_MNT parent || \
	_notrun "parent pointers required to test directory auto-repair"
_require_xfs_healer $SCRATCH_MNT --repair

filter_healer() {
	_filter_scratch | \
		grep 'Full repairs in progress' | \
		uniq
}

# Configure the filesystem for automatic repair of the filesystem.
$XFS_PROPERTY_PROG $SCRATCH_MNT set autofsck=repair >> $seqres.full

# Create a largeish directory
dblksz=$(_xfs_get_dir_blocksize "$SCRATCH_MNT")
echo testdata > $SCRATCH_MNT/a
mkdir -p "$SCRATCH_MNT/some/victimdir"
for ((i = 0; i < (dblksz / 255); i++)); do
	fname="$(printf "%0255d" "$i")"
	ln $SCRATCH_MNT/a $SCRATCH_MNT/some/victimdir/$fname
done

# Did we get at least two dir blocks?
dirsize=$(stat -c '%s' $SCRATCH_MNT/some/victimdir)
test "$dirsize" -gt "$dblksz" || echo "failed to create two-block directory"

# Break the directory, remount filesystem
_scratch_unmount
_scratch_xfs_db -x \
	-c 'path /some/victimdir' \
	-c 'bmap' \
	-c 'dblock 1' \
	-c 'blocktrash -z -0 -o 0 -x 2048 -y 2048 -n 2048' \
	-c 'path /a' \
	-c 'bmap -a' \
	-c 'ablock 1' \
	-c 'blocktrash -z -0 -o 0 -x 2048 -y 2048 -n 2048' \
	>> $seqres.full
_scratch_mount

_scratch_invoke_xfs_healer "$tmp.healer" --repair

# Access the broken directory to trigger a repair, then poll the directory
# for 5 seconds to see if it gets fixed without us needing to intervene.
ls $SCRATCH_MNT/some/victimdir > /dev/null 2> $tmp.err
_filter_scratch < $tmp.err
try=0
while [ $try -lt 50 ] && grep -q 'Structure needs cleaning' $tmp.err; do
	echo "try $try saw corruption" >> $seqres.full
	sleep 0.1
	ls $SCRATCH_MNT/some/victimdir > /dev/null 2> $tmp.err
	try=$((try + 1))
done
echo "try $try no longer saw corruption or gave up" >> $seqres.full
_filter_scratch < $tmp.err

# Wait for the background fixer to finish
svc="$(_xfs_scrub_svcname "$SCRATCH_MNT")"
_systemd_unit_wait "$svc"

# List the dirents of /victimdir and parent pointers of /a to see if they both
# stop reporting corruption
(ls $SCRATCH_MNT/some/victimdir ; $XFS_IO_PROG -c 'parent') > /dev/null 2> $tmp.err
try=0
while [ $try -lt 50 ] && grep -q 'Structure needs cleaning' $tmp.err; do
	echo "retry $try still saw corruption" >> $seqres.full
	sleep 0.1
	(ls $SCRATCH_MNT/some/victimdir ; $XFS_IO_PROG -c 'parent') > /dev/null 2> $tmp.err
	try=$((try + 1))
done
echo "retry $try no longer saw corruption or gave up" >> $seqres.full

# Unmount to kill the healer
_scratch_kill_xfs_healer
cat $tmp.healer >> $seqres.full
cat $tmp.healer | filter_healer

_exit 0
